# -*- coding: utf-8 -*-
"""Copia de mr-dbscan-challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKln2Itab289y19Zx_dCKmTbrLTXNc6w

# Challenge de Reproducibilidad: MR-DBSCAN
## Algoritmo Paralelo de Clustering por Densidad usando MapReduce

---

## Información del Proyecto

**Paper:** MR-DBSCAN: An Efficient Parallel Density-based Clustering Algorithm using MapReduce  
**Autores:** Yaobin He, Haoyu Tan, Wuman Luo, et al. (Shenzhen Institutes of Advanced Technology)  
**Dataset:** 1.9 billion GPS records (Shanghai taxi data) o sintético  
**Plataforma:** Hadoop + PySpark  

**Objetivo:** Reproducir el algoritmo MR-DBSCAN en 4 etapas usando MapReduce para clustering de datos espaciales a gran escala.

---

## Parámetros del Algoritmo

- **Eps (epsilon):** Radio máximo de vecindad
  - Limpieza de datos: 0.002 (elimina ruido/outliers)
  - Identificación de regiones densas: 0.0002 (clusters más específicos)

- **MinPts:** Número mínimo de puntos para formar un cluster
  - Limpieza: 1000 puntos
  - Regiones densas: 100 puntos

- **Particiones:** Grid-based partitioning
  - Strips por dimensión: 80-160 según Eps

---

## División de Tareas por Persona

| Rol | Responsabilidades |
|-----|-------------------|
| **Persona 1** | Etapa 1 (Preprocesamiento y Particionado) + Setup inicial |
| **Persona 2** | Etapa 2 (DBSCAN Local) + Etapa 3 (Detección de Cruces) |
| **Persona 3** | Etapa 4 (Fusión Global) + Validación y Reportes |

---

## Fases del Algoritmo MR-DBSCAN

El algoritmo se ejecuta en 4 etapas usando MapReduce:

1. **Stage 1 - Preprocesamiento:** Análisis del dataset y particionamiento en grid
2. **Stage 2 - DBSCAN Local:** Clustering independiente en cada partición
3. **Stage 3 - Detección de Cruces:** Identificar clusters que cruzan fronteras (MC Sets)
4. **Stage 4 - Fusión Global:** Unificar clusters y relabeling global

---

# PARTE 1: SETUP INICIAL Y CARGA DE DATOS
## Responsable: Jose

### Paso 1.1: Configuración del Entorno Spark

**¿Qué hace este paso?**

Este paso inicializa una sesión de Spark (SparkSession), que es el punto de entrada principal para trabajar con DataFrames y RDDs en PySpark. La sesión establece la conexión con el cluster Hadoop y configura el nombre de la aplicación para identificarla en el Hadoop NameNode.

**Detalles técnicos:**
- `SparkSession.builder` permite crear una nueva sesión de forma fluida
- `.appName()` asigna el nombre "MR-DBSCAN" que verás en la interfaz Hadoop
- `.getOrCreate()` obtiene una sesión existente o crea una nueva

**¿Por qué es importante?**
- Necesario para distribuir datos y código a los nodos del cluster
- Permite usar funciones paralelas de Spark en todo el código
"""

# Inicializar SparkSession
from pyspark.sql import SparkSession
import pyspark.sql.functions as F

def get_spark_session(app_name='MR-DBSCAN'):
    """
    Crea una nueva sesión de Spark o retorna la existente.

    Parámetros:
        app_name (str): Nombre de la aplicación para identificar en Hadoop

    Retorna:
        SparkSession: Sesión de Spark lista para usar
    """
    spark = SparkSession.builder \
        .appName(app_name) \
        .config("spark.sql.shuffle.partitions", "200") \
        .getOrCreate()

    # Configurar nivel de logging para reducir mensajes
    spark.sparkContext.setLogLevel("WARN")

    return spark

# Crear sesión
spark = get_spark_session()
print(f"✓ Sesión de Spark creada exitosamente")
print(f"  - Spark Version: {spark.version}")
print(f"  - Master: {spark.sparkContext.master()}")

"""
### 📌 Paso 1.2: Cargar y Preprocesar los Datos

**¿Qué hace este paso?**

Este paso:
1. **Carga o genera datos:** Si tienes un archivo CSV con GPS, lo carga. Si no, genera datos sintéticos que simulan coordenadas GPS (latitud y longitud)
2. **Normalización:** Transforma las coordenadas a un rango estándar (0-1) para facilitar el particionado
3. **Estructuras de datos:** Convierte los datos a un DataFrame de Pandas (para pre-procesamiento local) o Spark (para procesamiento distribuido)

**¿Por qué es importante?**
- El MR-DBSCAN requiere datos espaciales (lat, lon) en formato limpio
- La normalización es crucial para que el grid partitioning funcione correctamente
- Los datos limpios y bien estructurados son la base del algoritmo

**Datos de ejemplo:**
- Dataset original: 1.9 mil millones de GPS del taxi de Shanghai
- Para este ejemplo: 100,000 puntos sintéticos distribuidos aleatoriamente

"""

import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Opción 1: Si tienes un CSV con datos GPS, descomenta y modifica:
# data = pd.read_csv('ruta/a/tu/archivo.csv')
# data = data[['lon', 'lat']].copy()

# Opción 2: Generar datos sintéticos (para demostración)
n_points = 100000  # Número de puntos a generar
np.random.seed(42)  # Para reproducibilidad

# Simular coordenadas GPS de Shanghai (rango real)
data = pd.DataFrame({
    'lon': np.random.uniform(121.0, 122.0, size=n_points),  # Longitud
    'lat': np.random.uniform(30.9, 31.5, size=n_points)    # Latitud
})

# Normalizar coordenadas al rango [0, 1]
data['lon_norm'] = (data['lon'] - data['lon'].min()) / (data['lon'].max() - data['lon'].min())
data['lat_norm'] = (data['lat'] - data['lat'].min()) / (data['lat'].max() - data['lat'].min())

print(f"✓ Datos cargados exitosamente")
print(f"  - Número de puntos: {len(data):,}")
print(f"  - Rango Longitud: [{data['lon'].min():.6f}, {data['lon'].max():.6f}]")
print(f"  - Rango Latitud: [{data['lat'].min():.6f}, {data['lat'].max():.6f}]")
print(f"\nPrimeros 5 registros:")
print(data.head())

"""
---

# PARTE 2: PARTICIONADO EN GRID
## Responsable: Jose

### Paso 2.1: División del Dominio Espacial con Grid

**¿Qué hace este paso?**

Este es el corazón del Stage 1 del MR-DBSCAN. El particionamiento en grid:

1. **Divide el espacio:** Crea una malla 2D que cubre todo el área geográfica
2. **Asigna particiones:** Cada punto GPS recibe un ID de partición según su ubicación en la malla
3. **Equilibra carga:** Intenta que cada partición tenga aproximadamente la misma cantidad de datos

**Conceptos clave:**
- **n_strips:** Número de divisiones por dimensión (80-160 según el paper)
  - Más strips = particiones más pequeñas (mejor balance pero más réplicas en bordes)
  - Menos strips = particiones más grandes (menos comunicación pero desbalance)
- **lon_bin / lat_bin:** Índice de la celda en cada dimensión
- **partition_id:** Identificador único de la partición (combinación de lon_bin y lat_bin)

**¿Por qué es importante?**
- MapReduce distribuye datos a diferentes nodos según la partición
- El balance de carga afecta directamente el rendimiento paralelo
- Un particionamiento pobre causa "data skew" (algunos nodos reciben más datos)

**Ejemplo visual:**
```
Si n_strips=3, espacio 0-1 se divide en:
[0-0.33, 0.33-0.67, 0.67-1.0]

Un punto en (0.5, 0.8) recibe:
lon_bin = 1 (está en [0.33-0.67])
lat_bin = 2 (está en [0.67-1.0])
partition_id = "1_2"
```

"""

# Definir parámetros de particionamiento
n_strips = 120  # Óptimo según el paper para Eps grande (0.002)

# Crear bins para dividir el espacio normalizado [0, 1]
lon_bins = np.linspace(0, 1, n_strips + 1)
lat_bins = np.linspace(0, 1, n_strips + 1)

# Asignar cada punto a su bin (celda del grid)
data['lon_bin'] = np.digitize(data['lon_norm'], lon_bins) - 1
data['lat_bin'] = np.digitize(data['lat_norm'], lat_bins) - 1

# Crear identificador único de partición
data['partition_id'] = data['lon_bin'].astype(str) + '_' + data['lat_bin'].astype(str)

# Información del particionado
n_partitions = len(data['partition_id'].unique())
print(f"✓ Particionamiento completado")
print(f"  - Número de strips por dimensión: {n_strips}")
print(f"  - Total de particiones: {n_partitions}")
print(f"  - Puntos por partición (promedio): {len(data) / n_partitions:.1f}")
print(f"  - Particiones con datos: {(data['partition_id'].value_counts() > 0).sum()}")

# Mostrar distribución de datos entre particiones
print(f"\nDistribución de datos:")
partition_counts = data['partition_id'].value_counts()
print(f"  - Partición con más datos: {partition_counts.max()} puntos")
print(f"  - Partición con menos datos: {partition_counts.min()} puntos")
print(f"  - Desviación estándar: {partition_counts.std():.1f}")

"""
### Paso 2.2: Preparación de Datos para MapReduce

**¿Qué hace este paso?**

Prepara los datos para ser procesados en paralelo en Hadoop:

1. **Agrupa por partición:** Organiza todos los puntos que pertenecen a la misma partición
2. **Convierte a Spark DataFrame:** Transforma los datos de Pandas a Spark para procesamiento distribuido
3. **Repartición:** Distribuye las particiones entre los nodos del cluster Hadoop

**¿Por qué es importante?**
- MapReduce requiere datos en formato distribuido
- Spark DataFrame permite operaciones paralelas automáticas
- La repartición asegura que cada nodo reciba trabajo similar

"""

# Opción 1: Mantener en Pandas para procesamiento local
partition_groups = dict(list(data.groupby('partition_id')))
print(f"✓ Datos agrupados por partición")
print(f"  - Número de grupos: {len(partition_groups)}")
print(f"  - Ejemplo de keys: {list(partition_groups.keys())[:5]}")

# Opción 2: Convertir a Spark DataFrame para procesamiento distribuido
spark_df = spark.createDataFrame(data)
spark_df = spark_df.repartition('partition_id')  # Distribuir por partition_id

print(f"\n✓ Spark DataFrame creado")
print(f"  - Número de particiones Spark: {spark_df.rdd.getNumPartitions()}")
print(f"  - Total de registros: {spark_df.count():,}")
print(f"\nEstructura de datos:")
spark_df.printSchema()

"""
---

# PARTE 3: DBSCAN LOCAL Y GENERACIÓN DE MC SETS
## Responsable: Miguel

### Paso 3.1: DBSCAN Local en Cada Partición

**¿Qué hace este paso? (Stage 2 del paper)**

Este es el corazón del clustering. Para cada partición:

1. **Ejecuta DBSCAN localmente:** Aplica el algoritmo clásico DBSCAN a los puntos de la partición
2. **Clasifica puntos:** Etiqueta cada punto como:
   - **Core Point (C):** Tiene ≥ MinPts vecinos dentro de Eps
   - **Border Point (B):** Tiene < MinPts vecinos pero es vecino de un Core Point
   - **Noise (N):** No cumple ninguna condición (outlier)
3. **Genera clusters locales:** Crea cluster IDs locales por partición

**Parámetros importantes:**
- **Eps = 0.002:** Radio de búsqueda (distancia máxima a vecinos)
- **MinPts = 1000:** Mínimo número de puntos para ser Core Point

**Algoritmo DBSCAN en pseudocódigo:**
```
Para cada punto p no visitado:
  1. Si p tiene < MinPts vecinos → marcar como Noise
  2. Si p tiene ≥ MinPts vecinos → marcar como Core Point
  3. Expandir: recursivamente procesar todos sus vecinos
  4. Crear cluster cuando se termina la expansión
```

**¿Por qué es importante?**
- Cada nodo ejecuta esta operación independientemente (paralelismo real)
- Los resultados locales se combinan después en el Stage 4
- Reduce significativamente la complejidad computacional general

**Complejidad:**
- Tiempo: O(n * log n) con indexación espacial, O(n²) sin indexación
- Espacio: O(n) para almacenar el dataset

"""

from sklearn.cluster import DBSCAN
from sklearn.neighbors import KDTree
import scipy.spatial.distance as spatial_distance

# Definir parámetros DBSCAN
EPS = 0.002  # Radio de búsqueda en coordenadas normalizadas
MIN_SAMPLES = 1000  # Mínimo número de puntos para ser Core Point

print(f"Parámetros de DBSCAN:")
print(f"  - Eps: {EPS}")
print(f"  - MinPts: {MIN_SAMPLES}")

def local_dbscan_partition(partition_data, eps=EPS, min_samples=MIN_SAMPLES):
    """
    Ejecuta DBSCAN en una partición individual.

    Parámetros:
        partition_data: DataFrame con puntos de una partición
        eps: Radio de búsqueda
        min_samples: Mínimo de puntos para Core Point

    Retorna:
        array: Etiquetas de cluster locales para cada punto (-1 = noise)
    """
    coords = partition_data[['lon_norm', 'lat_norm']].values

    # Si la partición tiene pocos puntos, todos son noise
    if len(coords) < min_samples:
        return np.array([-1] * len(coords))

    # Ejecutar DBSCAN
    db = DBSCAN(eps=eps, min_samples=min_samples, metric='euclidean', n_jobs=-1)
    labels = db.fit_predict(coords)

    return labels

# Aplicar DBSCAN a cada partición
print(f"\n⏳ Ejecutando DBSCAN local en {n_partitions} particiones...")

data['local_cluster'] = -1  # Inicializar

for partition_id, group_idx in data.groupby('partition_id').groups.items():
    group = data.loc[group_idx]
    labels = local_dbscan_partition(group)
    data.loc[group_idx, 'local_cluster'] = labels

print(f"✓ DBSCAN local completado")
print(f"  - Puntos en clusters: {(data['local_cluster'] != -1).sum():,}")
print(f"  - Puntos noise/outliers: {(data['local_cluster'] == -1).sum():,}")
print(f"  - Total de clusters locales: {data['local_cluster'].max() + 1:.0f}")

# Mostrar estadísticas por partición
print(f"\nEstadísticas por partición:")
stats = data.groupby('partition_id').agg({
    'local_cluster': lambda x: (x != -1).sum(),
    'partition_id': 'count'
}).rename(columns={'local_cluster': 'clusters', 'partition_id': 'total_points'})
stats['noise'] = stats['total_points'] - stats['clusters']
print(stats.head(10))

"""
### Paso 3.2: Identificación de Puntos Frontera (MC Sets)

**¿Qué hace este paso? (Preparación para Stage 3)**

Identifica puntos especiales que **cruzan fronteras entre particiones**:

1. **Puntos frontera:** Puntos cuyo vecindario Eps-distance cruza hacia otra partición
2. **MC Sets (Merge Candidate Sets):** Conjuntos de puntos que potencialmente deben fusionarse
3. **Clasificación:** Marca los puntos que necesitarán procesamiento especial

**¿Por qué es importante?**
- DBSCAN local NO ve puntos en otras particiones
- Dos clusters en particiones vecinas podrían ser el MISMO cluster globalmente
- Necesitamos identificar estos casos ANTES de hacer la fusión

**Concepto clave - El problema de las fronteras:**

```
Partición A        |  Partición B
    ●●●●●●●●●●●●●●|●●●●●●●●●●●●●
    ●●●●●●●●●●●●●●|●●●●●●●●●●●●●

Local en A: cluster 1
Local en B: cluster 1
Pero podrían ser el MISMO cluster si un punto de A está cerca de B

→ Los puntos cerca de la frontera deben compararse entre particiones
```

"""

# Identificar puntos frontera (dentro de Eps de la frontera de la partición)
def identify_border_points(partition_data, eps=EPS):
    """
    Identifica puntos de una partición que están cerca de sus fronteras.

    Un punto es "frontera" si su vecindario Eps puede incluir puntos de otras particiones.
    """
    coords = partition_data[['lon_norm', 'lat_norm']].values

    if len(coords) == 0:
        return np.array([], dtype=bool)

    # Obtener límites de la partición (aproximado usando percentiles)
    lon_min, lon_max = coords[:, 0].min(), coords[:, 0].max()
    lat_min, lat_max = coords[:, 1].min(), coords[:, 1].max()

    # Marcar como frontera si está dentro de Eps de cualquier borde
    is_border = (
        (coords[:, 0] < lon_min + eps) |  # Cerca borde oeste
        (coords[:, 0] > lon_max - eps) |  # Cerca borde este
        (coords[:, 1] < lat_min + eps) |  # Cerca borde sur
        (coords[:, 1] > lat_max - eps)    # Cerca borde norte
    )

    return is_border

# Aplicar a cada partición
print(f"⏳ Identificando puntos frontera...")
data['is_border'] = False

for partition_id, group_idx in data.groupby('partition_id').groups.items():
    group = data.loc[group_idx]
    border_flags = identify_border_points(group)
    data.loc[group_idx, 'is_border'] = border_flags

# Mostrar resultados
n_border = data['is_border'].sum()
pct_border = 100 * n_border / len(data)

print(f"✓ Puntos frontera identificados")
print(f"  - Total puntos frontera: {n_border:,} ({pct_border:.1f}%)")
print(f"  - Puntos internos: {(~data['is_border']).sum():,}")

# Crear MC Sets (Merge Candidate Sets)
# Estos son pares de clusters que potencialmente deben fusionarse
mc_sets = []

for partition_id, group_idx in data.groupby('partition_id').groups.items():
    group = data.loc[group_idx]
    border_points = group[group['is_border']]

    if len(border_points) > 0:
        for idx, row in border_points.iterrows():
            if row['local_cluster'] != -1:  # No contar noise points
                mc_sets.append({
                    'partition_id': partition_id,
                    'point_id': idx,
                    'cluster_id': row['local_cluster'],
                    'lon': row['lon_norm'],
                    'lat': row['lat_norm']
                })

mc_df = pd.DataFrame(mc_sets)
print(f"\n✓ MC Sets (Merge Candidates) creados")
print(f"  - Total de candidatos para fusión: {len(mc_df):,}")
if len(mc_df) > 0:
    print(f"  - Clusters únicos en MC: {mc_df['cluster_id'].nunique()}")
    print(f"  - Particiones con candidatos: {mc_df['partition_id'].nunique()}")